apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescheduler
  namespace: kube-system
  labels:
    application: rescheduler
    version: v0.4.0
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: rescheduler
  replicas: 1
  template:
    metadata:
      labels:
        application: rescheduler
        version: v0.4.0
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: system
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: rescheduler
        image: registry.opensource.zalan.do/teapot/rescheduler:v0.4.0
        resources:
          requests:
            cpu: 25m
            memory: 100Mi
          limits:
            cpu: 25m
            memory: 100Mi
