# for github.com
approvals:
  minimum: 2
  from:
    users:
      - aermakov-zalando
      - arjunrn
      - gargravarr
      - hjacobs
      - jrake-revelant
      - linki
      - mikkeloscar
      - muaazsaleem
      - njuettner
      - szuecs

X-Zalando-Team: "teapot"
