{{ if eq .ConfigItems.vpa_enabled "true" }}
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: metrics-server-vpa
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: metrics-server
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: metrics-server
      maxAllowed:
        memory: {{if index .ConfigItems "prometheus_mem"}}{{.ConfigItems.prometheus_mem}}{{else}}4000Mi{{end}}
{{ end }}
