apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    application: cluster-autoscaler
    version: v0.3.2
spec:
  replicas: 1
  selector:
    matchLabels:
      application: cluster-autoscaler
  template:
    metadata:
      labels:
        application: cluster-autoscaler
        version: v0.3.2
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
        iam.amazonaws.com/role: "{{ .LocalID }}-app-autoscaler"
    spec:
      containers:
        - image: registry.opensource.zalan.do/teapot/aws-k8s-cluster-autoscaler:0.3.2
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 50Mi
          command:
            - ./cluster-autoscaler
            - --v=9
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --leader-elect=false
            - --scale-down-unneeded-time=45m0s
          env:
            - name: AWS_REGION
              value: {{ .Region }}
          imagePullPolicy: "Always"
