{{ if eq .Cluster.ConfigItems.teapot_admission_controller_service_account_iam "false" }}
apiVersion: zalando.org/v1
kind: AWSIAMRole
metadata:
  name: aws-node-decommissioner-aws-iam-credentials
  namespace: default
spec:
  roleReference: {{.LocalID}}-aws-node-decommissioner
{{ end }}
