{{ if ne .Environment "production" }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-node-decommissioner
  labels:
    application: aws-node-decommissioner
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: aws-node-decommissioner
{{ if eq .Cluster.ConfigItems.teapot_admission_controller_service_account_iam "false" }}
          annotations:
            iam.amazonaws.com/role: {{.LocalID}}-aws-node-decommissioner
{{ end }}
        spec:
          serviceAccountName: aws-node-decommissioner
          restartPolicy: Never
          containers:
          - name: aws-node-decommissioner
            image: registry.opensource.zalan.do/teapot/aws-node-decommissioner:master-75e9979d
            args:
              - --debug
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
{{ end }}
