apiVersion: poc.autoscaling.k8s.io/v1alpha1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: prometheus
  updatePolicy:
    updateMode: Auto
