apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "zmon-worker"
  namespace: "kube-system"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        application: "zmon-worker"
        version: "v0.1"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
        - name: zmon-worker
          image: "pierone.stups.zalan.do/stups/zmon-worker:zv195"
          env:
            - name: WORKER_TEAM
              value: "{{ .ConfigItems.account_alias }}"
            - name: WORKER_ZMON_QUEUES
              value: zmon:queue:default/25
            - name: WORKER_REDIS_SERVERS
              value: zmon-redis:6379

            - name: OAUTH2_ACCESS_TOKEN_URL
              value: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
            - name: CREDENTIALS_DIR
              value: /meta/credentials

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: true

        - name: gerry
          image: registry.opensource.zalan.do/teapot/gerry:v0.0.8
          args:
            - /meta/credentials
            - --application-id=secretary
            - --mint-bucket=s3://{{ .ConfigItems.gerry_mint_bucket }}

          volumeMounts:
            - name: credentials
              mountPath: /meta/credentials
              readOnly: false

      volumes:
        - name: credentials
          emptyDir:
            medium: Memory
