apiVersion: v1
kind: ConfigMap
metadata:
  name: scalyr-config-base
  namespace: kube-system
data:
  scalyr.config: |
    {
      "import_vars": ["WATCHER_SCALYR_API_KEY", "WATCHER_CLUSTER_ID"],

      "api_key": "$WATCHER_SCALYR_API_KEY",

      "server_attributes": {
          "serverHost": "$WATCHER_CLUSTER_ID"
      },

      "implicit_metric_monitor": false,
      "implicit_agent_process_metrics_monitor": false,

      "logs": [],
      "monitors": []
    }
