apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /mnt/fluentd-logs/**/*.log
      pos_file /mnt/posfiles/kubernetes.pos
      read_from_head true
      tag kubernetes.*
      <parse>
        @type json
        time_type string
        time_format %iso8601
        keep_time_key true
      </parse>
    </source>

    <filter kubernetes.**>
      @type age
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      <record>
        # s3_path is: ${application}/${component}/${namespace}/${environment}/${version}/${cont_name}
        s3_path  ${tag_parts[4]}/${tag_parts[5]}/${tag_parts[6]}/${tag_parts[7]}/${tag_parts[8]}/${tag_parts[9]}
        pod      ${tag_parts[10]}
      </record>
    </filter>

    <match kubernetes.**>
      @type s3
      s3_bucket {{ index .ConfigItems "logging_s3_bucket" }}
      s3_region eu-central-1
      <instance_profile_credentials>
        retries 10
      </instance_profile_credentials>
      s3_object_key_format kubernetes/${s3_path}/%Y/%m/%d/%H/${pod}/%Y%m%dT%H%M_%{index}.%{file_extension}
      <buffer time,s3_path,pod>
        @type file
        path /mnt/buffer/kubernetes/
        timekey 5m
        timekey_wait 1m
        timekey_use_utc true
        chunk_limit_size 4MB
        total_limit_size 1GB
        flush_at_shutdown true
        flush_thread_count 10
        flush_thread_burst_interval 0.1
      </buffer>
      <format>
        @type csv
        fields time,log
      </format>
    </match>
