{{ if eq .ConfigItems.vpa_enabled "true" }}
apiVersion: poc.autoscaling.k8s.io/v1alpha1
kind: VerticalPodAutoscaler
metadata:
  name: metrics-server-vpa
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: metrics-server
  updatePolicy:
    updateMode: "Auto"
{{ end }}
