{{ if eq .ConfigItems.vpa_enabled "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    application: vpa-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vpa-recommender
  template:
    metadata:
      labels:
        application: vpa-recommender
    spec:
      serviceAccountName: system
      containers:
      - name: recommender
        image: registry.opensource.zalan.do/teapot/vpa-recommender:d4fc72e
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 1000Mi
        ports:
        - containerPort: 8080
{{ end }}
