{{ if eq .ConfigItems.vpa_enabled "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    application: vpa-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vpa-updater
  template:
    metadata:
      labels:
        application: vpa-updater
    spec:
      serviceAccountName: system
      containers:
      - name: updater
        image: pierone.stups.zalan.do/teapot/vpa-updater:366b393
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 1000Mi
        ports:
        - containerPort: 8080
{{ end }}
