AWSTemplateFormatVersion: 2010-09-09
Description: Kubernetes karpenter based worker node pool type
Metadata:
  Tags:
    InfrastructureComponent: "true"

Resources:
  # create InstanceProfile wrapper on NodeRole
  KarpenterNodeInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: "{{ .Cluster.ID | awsValidID }}-{{ .NodePool.Name }}-InstanceProfile"
      Path: "/"
      Roles:
        - !ImportValue '{{ .Cluster.ID }}:worker-iam-role'
