apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-lifecycle-metrics
  namespace: kube-system
  labels:
    application: kubernetes-lifecycle-metrics
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kubernetes-lifecycle-metrics
  template:
    metadata:
      labels:
        application: kubernetes-lifecycle-metrics
      annotations:
        kubernetes-log-watcher/scalyr-parser: '[{"container": "kubernetes-lifecycle-metrics", "parser": "json"}]'
    spec:
      containers:
        - name: kubernetes-lifecycle-metrics
          image: "pierone.stups.zalan.do/teapot/kubernetes-lifecycle-metrics:pr-1-30"
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
