apiVersion: v1
kind: Service
metadata:
  labels:
    application: kubernetes-lifecycle-metrics
  name: kubernetes-lifecycle-metrics
  namespace: kube-system
spec:
  selector:
    application: kubernetes-lifecycle-metrics
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
