---
# Source: kubenurse/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubenurse"
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
---
# Source: kubenurse/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubenurse"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubenurse"
subjects:
- kind: ServiceAccount
  name: "kubenurse"
  namespace: kubenurse
---
# Source: kubenurse/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "kubenurse"
  namespace: kubenurse
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
# Source: kubenurse/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "kubenurse"
  namespace: kubenurse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "kubenurse"
subjects:
- kind: ServiceAccount
  name: "kubenurse"
  namespace: kubenurse
