{{ if index .ConfigItems "efsid" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
  namespace: kube-system
data:
  file.system.id: "{{ .ConfigItems.efsid }}"
  aws.region: "{{ .Region }}"
  provisioner.name: external-storage.alpha.kubernetes.io/aws-efs
{{ end }}
