# example: remove the app-ingress-controller deployment from kube-system
pre_apply:
- name: skipper-ingress
  namespace: kube-system
  kind: daemonset

# everything defined under here will be deleted before applying the manifests
#pre_apply: []

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: coredns
  namespace: kube-system
  kind: deployment
- name: cluster-dns
  namespace: kube-system
  kind: poddisruptionbudget
- name: dnsmasq-node
  namespace: kube-system
  kind: daemonset
- name: kube-dns-local
  namespace: kube-system
  kind: service
